"""
app.py - REST API for the customer intelligence system (PDF §11 "API Layer").

Endpoints:
    POST /process-customer-message   {"message": "..."} -> full analysis (PDF §5 output)
    GET  /health                     is the API up?
    GET  /docs                       interactive documentation (generated by FastAPI)

Before running:
    pip install fastapi uvicorn

Run (from the project folder):
    uvicorn app:app --reload
Then open http://127.0.0.1:8000/docs
"""

from typing import List

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

from decision import load_config
from llm import MODEL_NAME
from pipeline import process


# Load the rules once when the server starts, not on every request.
config = load_config()

app = FastAPI(
    title="Customer Intelligence API",
    description="Analyzes a bank customer message: intents, priority, routing, action and a grounded reply.",
    version="1.0",
)


class MessageRequest(BaseModel):
    """What the client sends."""
    message: str = Field(min_length=1, max_length=2000, examples=["I was charged twice for the same transaction."])


class AnalysisResponse(BaseModel):
    """What the API sends back: the PDF §5 output plus the sources used."""
    intents: List[str]
    issue_type: str
    priority: str
    entities: List[str]
    routing: str
    suggested_action: str
    response: str
    sources: List[str]


@app.get("/health")
def health():
    """Simple check that the API is running."""
    return {"status": "ok", "model": MODEL_NAME}


@app.post("/process-customer-message", response_model=AnalysisResponse)
def process_customer_message(request: MessageRequest):
    """Run one customer message through the full pipeline."""
    message = request.message.strip()
    if message == "":
        raise HTTPException(status_code=422, detail="Message must not be empty.")

    try:
        result = process(message, config)  # process() also logs the request
    except Exception as error:
        # Most likely cause: Ollama is not running or the model is not downloaded.
        raise HTTPException(
            status_code=503,
            detail="The analysis service is unavailable: " + repr(error),
        )
    return result
