"""
app.py - web app and REST API for the customer intelligence system (PDF §11 "API Layer").

Endpoints:
    POST /process-customer-message   {"message": "..."} -> full analysis (PDF §5 output)
    GET  /health                     is the API up, and which model is it using?
    GET  /docs                       interactive API documentation (generated by FastAPI)

The web page is a separate React app in frontend/ (it calls this API from another address,
which is why CORS is configured below).

Run (from the project folder):
    python -m uvicorn app:app --reload
Then open http://127.0.0.1:8000/docs
"""

import os
import threading
import time
from typing import List

from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from decision import load_config
from llm import MODEL_NAME, PROVIDER
from pipeline import process
from retriever import build_index


# Load the rules once when the server starts, not on every request.
config = load_config()

# Hosted mode: build the in-memory search index in the background as soon as the server starts,
# so the first visitor does not wait for it. (Local mode keeps its index in chroma_db/ on disk.)
# ponytail: a request that arrives before this finishes builds the index itself; no lock needed at this size.
if PROVIDER == "groq":
    threading.Thread(target=build_index, daemon=True).start()

app = FastAPI(
    title="Customer Intelligence API",
    description="Analyzes a bank customer message: intents, priority, routing, action and a grounded reply.",
    version="1.2",
)

# CORS: browsers only let a web page call an API on a different address if the API allows it.
# ALLOWED_ORIGINS = comma-separated list of frontend addresses, e.g. "https://my-site.onrender.com".
# The default allows the Vite dev server on this computer.
allowed_origins = os.getenv("ALLOWED_ORIGINS", "http://localhost:5173,http://127.0.0.1:5173").split(",")
app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origins,
    allow_methods=["GET", "POST"],
    allow_headers=["Content-Type"],
)


# ---------------------------------------------------------------- rate limiting
# Protects the free LLM quota on the public demo from being used up by one visitor.
# ponytail: in-memory, per server process; resets on restart. Fine for one small instance,
# use Redis or the host's rate limiting if the app is ever scaled to several instances.
MAX_PER_MINUTE_PER_VISITOR = 5
MAX_PER_DAY_PER_VISITOR = 50
MAX_PER_DAY_TOTAL = 400        # each message = 2 LLM calls; keeps the whole demo under the free daily limit

request_times_by_visitor = {}  # visitor IP -> list of request times (seconds)
request_times_all = []         # request times for everyone


def get_visitor_ip(request):
    """The visitor's IP address. Behind a host like Render, the real one is in X-Forwarded-For."""
    forwarded = request.headers.get("x-forwarded-for")
    if forwarded:
        return forwarded.split(",")[0].strip()
    return request.client.host


def keep_recent(times, now, seconds):
    """Return only the times that happened within the last `seconds`."""
    recent = []
    for t in times:
        if now - t < seconds:
            recent.append(t)
    return recent


def count_recent(times, now, seconds):
    """How many of the times happened within the last `seconds`."""
    return len(keep_recent(times, now, seconds))


def check_rate_limit(ip):
    """Raise a 429 error if this visitor (or everyone together) has made too many requests."""
    global request_times_all
    now = time.time()
    one_day = 24 * 60 * 60

    request_times_all = keep_recent(request_times_all, now, one_day)
    if len(request_times_all) >= MAX_PER_DAY_TOTAL:
        raise HTTPException(status_code=429, detail="The demo has reached its daily limit. Please come back tomorrow.")

    visitor_times = keep_recent(request_times_by_visitor.get(ip, []), now, one_day)
    if count_recent(visitor_times, now, 60) >= MAX_PER_MINUTE_PER_VISITOR:
        raise HTTPException(status_code=429, detail="Too many requests. Please wait a minute and try again.")
    if len(visitor_times) >= MAX_PER_DAY_PER_VISITOR:
        raise HTTPException(status_code=429, detail="You have reached today's limit for this demo. Thanks for trying it!")

    visitor_times.append(now)
    request_times_by_visitor[ip] = visitor_times
    request_times_all.append(now)


# ---------------------------------------------------------------- request / response shapes

class MessageRequest(BaseModel):
    """What the client sends."""
    message: str = Field(min_length=1, max_length=2000, examples=["I was charged twice for the same transaction."])


class AnalysisResponse(BaseModel):
    """What the API sends back: the PDF §5 output plus the sources used."""
    intents: List[str]
    issue_type: str
    priority: str
    entities: List[str]
    routing: str
    suggested_action: str
    response: str
    sources: List[str]


# ---------------------------------------------------------------- endpoints

@app.get("/", include_in_schema=False)
def home():
    """The API has no page of its own; point visitors to the docs."""
    return {"message": "Customer Intelligence API. See /docs for the endpoints."}


@app.get("/health")
def health():
    """Simple check that the API is running, and which model it uses."""
    return {"status": "ok", "provider": PROVIDER, "model": MODEL_NAME}


@app.post("/process-customer-message", response_model=AnalysisResponse)
def process_customer_message(body: MessageRequest, request: Request):
    """Run one customer message through the full pipeline."""
    message = body.message.strip()
    if message == "":
        raise HTTPException(status_code=422, detail="Message must not be empty.")

    check_rate_limit(get_visitor_ip(request))

    try:
        result = process(message, config)  # process() also logs the request
    except Exception as error:
        # Most likely cause: the model service is not reachable (Ollama not running, Groq down or key invalid).
        # The details go to the server log, not to the visitor.
        print("Pipeline error:", repr(error))
        raise HTTPException(status_code=503, detail="The analysis service is temporarily unavailable.")
    return result
